### ISSUE TITLE
add list of chats

### ISSUE THREAD

**Issue by kristjanjansen** [kuressaareametikool/kig22-food#7]
https://www.figma.com/file/SHj51eMTSLlBRMsbVW4Upi/FOOD-TINDER?node-id=0%3A1

<img width="302" alt="Screenshot 2022-05-21 at 09 08 10" src="https://user-images.githubusercontent.com/241603/169638403-b5898466-7c06-420d-a680-6a9f2330da18.png">

Here are multiple areas that might focus, I'd first create a "card" of a chat

<img width="283" alt="Screenshot 2022-05-21 at 09 08 10 2" src="https://user-images.githubusercontent.com/241603/169638464-3fe04b90-1702-4392-ba91-cea5a06416c1.png">

1. Create a `div` with a class that has basic layout in place. I'd go for:

```css
.YourCardClassName {
  display: flex;
  gap: 16px;
}
.YourCardClassName:first-child {
  flex-shrink: 0; /* This prevents the image from deforming by flexbox */
}
```

2. Add image from Unsplash and make it fully round

    Use the `object-fit` and `aspect-ratio` bonus material from #6 

   See whenver `border-radius: 100000px` or `border-radius: 100%` makes the image fully round
 
 3. Add right-side text
 
 4. SUPER-BONUS: Instead of hardcoding the chats data, define the data in the body tag:
 
 ```
 v-scope="{chats: [{ src: 'image-link-goes-here', name: 'Mustafa' },{ src: 'image-link-goes-here', name: 'Sam' }]}"
 ```
 
 ... and later use this to loop over your data and display multiple chats:
 
 ```
 <div v-for="chat in chats" class="YourCardClassName">
   <img :src="chat.src" />
   <div>{{ chat.name }}</div>
 </div>
 ```
